spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      hbm2ddl.auto: update
      show_sql: true
